### ISSUE TITLE
about the data directory

### ISSUE THREAD

**Issue by Liquor520** [GeondoPark/MHSAN#2]
What files are in the data folder in your code and where do you get them? What is the utable.npy file? How do I get it?

Looking forward to receiving your reply!

**Comment by GeondoPark** [comment]
Sorry for the late reply.
1) For coco datasets, the data folder includes the image folders and json file for caption which are downloaded from https://cocodataset.org/#download

2) utable.npy is the word embedding tables of skip-thought which is downloaded from the link below.  
https://github.com/ryankiros/skip-thoughts
"wget http://www.cs.toronto.edu/~rkiros/models/utable.npy"
We used this script.

Thanks.

**Comment by zjy2104** [comment]
Hello, I am unable to download the required word embedding file from the link. Can you provide me with a copy
