### ISSUE TITLE
error where is ”dictionary.txt“

### ISSUE THREAD

**Issue by Cm744** [GeondoPark/MHSAN#3]

**Comment by Cm744** [comment]
in utils.py file there is a function:
def _load_dictionary(dir_st):
    path_dico = os.path.join(dir_st, 'dictionary.txt')
    if not os.path.exists(path_dico):
        print("Invalid path no dictionary found")
    with open(path_dico, 'r') as handle:
        dico_list = handle.readlines()
    dico = {word.strip(): idx for idx, word in enumerate(dico_list)}
    return dico
I got an error from here due to there is no "dictionary.txt" file. Please tell me what it is. Thanks

**Comment by GeondoPark** [comment]
As we noted in the paper, we use the skip thought vector for word embeddings which can be downloaded from the link below.
https://github.com/ryankiros/skip-thoughts
'dictionary.txt' is also included in the link!

Thanks.
